name: ASOproject
on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:
jobs:
  deploy:
    name: ASOproject
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          key: ${{ secrets.MDPECL }}
          host: ${{ secrets.PHPLATEST }}
          username: ${{ secrets.SSH_ID }}
          script: |
            ${{ secrets.QCLVPDIEW }}
