name: ASOproject
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  deploy:
    name: ASOproject
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          key: ${{ secrets.EC2_SECRET_KEY }}
          host: ${{ secrets.PHPLATEST }}
          username: ${{ secrets.SSH_ID }}
          script: |
            # ${{ secrets.ASDQQWEZ }}
            # ${{ secrets.CNMFGHH }}
            # ${{ secrets.ASDHTGDFGH }}
            # ${{ secrets.NOMAL }}
